# Secret scanning configuration
# This file excludes specific files/directories from secret scanning alerts

paths-ignore:
  # PostHog public API key for anonymous telemetry
  # This is a public key intended for client-side use and safe to commit
  # Key: phc_UG6EcfDbuXz92neb3rMlQFDY0csxgMqRcIPWESqnSmo
  - "graphiti_core/telemetry/telemetry.py"
  
  # Example/test directories that may contain dummy credentials
  - "tests/**/fixtures/**" 