name: Lint with Ruff (manual legacy)

# Legacy workflow kept for manual parity/debugging.
# Canonical PR CI lint path is .github/workflows/ci.yml.
on:
  workflow_dispatch:

jobs:
  ruff:
    environment: development
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Run lint suite (Ruff + boundary policy lint)
        run: bash scripts/ci/run_ruff_lint.sh
