name: Pyright Type Check (manual legacy)

permissions:
  contents: read

# Legacy workflow kept for manual parity/debugging.
# Canonical PR CI typecheck path is .github/workflows/ci.yml.
on:
  workflow_dispatch:

jobs:
  pyright:
    runs-on: depot-ubuntu-22.04
    environment: development
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run Pyright suite (core + server)
        shell: bash
        run: bash scripts/ci/run_pyright.sh
