name: Build image
 
on:
  push:
    tags: ["v*.*.*"]
 
jobs:
  docker-image:
    environment:
      name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          context: .
          push: true
          tags: zepai/graph-service:latest