name: Template Compliance Check

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  check-template-compliance:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check Issue Template Compliance
      if: github.event_name == 'issues'
      uses: anthropics/claude-code-github-action@v1
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        prompt: |
          You are helping maintain template compliance for GitHub issues and PRs in the Graphiti project.
          
          Review the following issue against the bug report template requirements:
          
          Required sections:
          - Bug Description
          - Steps to Reproduce (with code example)
          - Expected Behavior
          - Actual Behavior
          - Environment (Graphiti version, Python version, OS, Database backend, LLM provider & model)
          - Installation Method
          - Error Messages/Traceback
          - Configuration
          - Additional Context
          
          Issue Title: ${{ github.event.issue.title }}
          Issue Body:
          ${{ github.event.issue.body }}
          
          Analyze if the issue follows the template and has sufficient detail. If missing important sections or details, provide a helpful comment asking the author to add the missing information. Be friendly and specific about what's needed.
          
          If the issue is well-formed, provide a brief thank you comment for their submission.
          
          If the issue needs improvements, provide a markdown comment that:
          1. Thanks the author for the report
          2. Specifically lists what sections or details are missing
          3. Explains why that information is helpful for debugging
          4. Asks them to update the issue description
        
        comment-on-issue: true
        issue-number: ${{ github.event.issue.number }}
    
    - name: Check PR Template Compliance
      if: github.event_name == 'pull_request'
      uses: anthropics/claude-code-github-action@v1
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        prompt: |
          You are helping maintain template compliance for GitHub issues and PRs in the Graphiti project.
          
          Review the following PR against the template requirements:
          
          Required sections:
          - Summary
          - Type of Change (checked box)
          - Objective (required for new features and performance improvements)
          - Testing (with checkboxes)
          - Breaking Changes (checkbox and description if applicable)
          - Checklist (with checkboxes)
          - Related Issues
          
          PR Title: ${{ github.event.pull_request.title }}
          PR Body:
          ${{ github.event.pull_request.body }}
          
          Analyze if the PR follows the template and has sufficient detail. Pay special attention to:
          - If "New feature" or "Performance improvement" is selected, ensure Objective section is filled
          - Testing checkboxes should be appropriately checked
          - Breaking changes should be properly documented if the checkbox is checked
          
          If the PR is well-formed, provide a brief thank you comment for their contribution.
          
          If the PR needs improvements, provide a markdown comment that:
          1. Thanks the author for the contribution
          2. Specifically lists what sections or details are missing
          3. Explains why that information is helpful for review
          4. Asks them to update the PR description
        
        comment-on-pr: true
        pr-number: ${{ github.event.pull_request.number }}